name: quizz
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.3.0
  google_sign_in: ^5.4.3
  firebase_messaging: ^14.2.6
  json_annotation: ^4.5.0
  rxdart: ^0.27.7
  provider: ^6.0.5
  # google_sign_in: 5.3.3
  # sign_in_with_apple: 4.0.0
  # crypto: 3.0.1
  # font_awesome_flutter: 10.1.0
  # google_fonts: 3.0.1
  # provider: 6.0.3
  # rxdart: 0.27.4
  # json_annotation: 4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  build_runner: 2.1.11
  json_serializable: 6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif